In [7]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.pipeline import Pipeline

In [75]:
docs = ['one two', 'two', 'three', 'four']

In [76]:
vectorizer = Pipeline(
    [('count', CountVectorizer()),
    ('transform', TfidfTransformer())]
)

In [77]:
vectorizer.fit(docs)

Pipeline(steps=[('count', CountVectorizer()),
                ('transform', TfidfTransformer())])

In [78]:
vectorizer['transform'].idf_

array([1.91629073, 1.91629073, 1.91629073, 1.51082562])

In [51]:
vectorizer['count'].vocabulary_

{'one': 1, 'two': 3, 'three': 2, 'four': 0}

In [18]:
import numpy as np

In [52]:
cm = vectorizer['count'].transform(['One two three', 'two one'])

In [55]:
cm.toarray()

array([[0, 1, 1, 1],
       [0, 1, 0, 1]], dtype=int64)

In [56]:
cm.indices

array([1, 2, 3, 1, 3])

In [57]:
df =np.bincount(cm.indices)

In [58]:
df

array([0, 2, 1, 2], dtype=int64)

In [59]:
n = 2

In [66]:
idf = np.log(n/df) + 1
idf

array([       inf, 1.        , 1.69314718, 1.        ])

In [67]:
import scipy.sparse as sp

In [72]:
idf_diag = sp.diags(idf).toarray()
idf_diag

array([[       inf, 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.69314718, 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [71]:
cm.toarray()

array([[0, 1, 1, 1],
       [0, 1, 0, 1]], dtype=int64)

In [73]:
np.dot(cm.toarray(), idf_diag)

array([[       nan, 1.        , 1.69314718, 1.        ],
       [       nan, 1.        , 0.        , 1.        ]])

In [74]:
np.dot(idf_diag, cm.toarray())

ValueError: shapes (4,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)